### ISSUE TITLE
no vendor?

### ISSUE THREAD

**Issue by picepice** [rosemalejohn/dnsc-hris#1]
Error po.. dahil sa vendor

**Comment by rosemalejohn** [comment]
If you have composer install in your local machine, try installing the project dependencies via `composer install` and the vendor folder will appear.

**Comment by picepice** [comment]
sorry my bad.. 👍

**Comment by picepice** [comment]
default admin login boss?

**Comment by rosemalejohn** [comment]
I forgot, but try u: 237, p: 237

**Comment by picepice** [comment]
thanks again..
