### ISSUE TITLE
bower components

### ISSUE THREAD

**Issue by picepice** [rosemalejohn/dnsc-hris#2]
Hello again..

how do i install this? ive tried gulp --production but theres a lot of problem..

Fetching Styles Source Files...
   - public\bower_components\bootstrap\dist\css\bootstrap.css <-- Not Found
   - public\bower_components\font-awesome\css\font-awesome.css <-- Not Found
   - public\bower_components\animate.css\animate.css <-- Not Found
   - public\bower_components\sweetalert\dist\sweetalert.css <-- Not Found
   - public\bower_components\sweetalert\themes\facebook\facebook.css <-- Not Fou
nd
   - public\dist\css\style-v2.css
   - public\dist\css\theme.css
   - public\bower_components\ladda\dist\ladda-themeless.min.css <-- Not Found

Saving To...
   - public/css/all.min.css

[19:43:18] Finished 'default' after 686 ms
[19:43:20] gulp-notify: [Laravel Elixir] Stylesheets Merged!
[19:43:20] Finished 'styles' after 2.73 s
[19:43:20] Starting 'copy'...

Fetching Copy Source Files...
   - public/bower_components/font-awesome/fonts/**/*
   - public/bower_components/bootstrap/fonts/**/*

Saving To...
   - public/fonts

[19:43:20] Finished 'copy' after 7.9 ms
[19:43:20] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\bower_components\jquery\dist\jquery.js <-- Not Found
   - public\bower_components\bootstrap\dist\js\bootstrap.js <-- Not Found
   - public\bower_components\moment\min\moment.min.js <-- Not Found

Saving To...
   - public/js/main.min.js

[19:43:20] Finished 'scripts' after 673 ms
[19:43:20] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\dist\js\app.js
   - public\bower_components\nanoscroller\bin\javascripts\jquery.nanoscroller.js
 <-- Not Found
   - public\bower_components\metisMenu\dist\metisMenu.js <-- Not Found
   - public\bower_components\fastclick\lib\fastclick.js <-- Not Found
   - public\bower_components\bootbox.js\bootbox.js <-- Not Found
   - public\bower_components\sweetalert\dist\sweetalert.min.js <-- Not Found
   - public\dist\js\hris.js

Saving To...
   - public/js/all.min.js

[19:43:21] gulp-notify: [Laravel Elixir] Scripts Merged!
[19:43:21] Finished 'scripts' after 587 ms
[19:43:21] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\dist\js\notifications.js

Saving To...
   - public/js/notifications.js

[19:43:21] gulp-notify: [Laravel Elixir] Scripts Merged!
[19:43:21] Finished 'scripts' after 30 ms
[19:43:21] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\dist\plugins\bootstrap-wizard\jquery.bootstrap.wizard.min.js
   - public\dist\plugins\bootstrap-validator\bootstrapValidator.min.js
   - public\dist\plugins\bootstrap-datepicker\dist\js\bootstrap-datepicker.min.j
s
   - public\bower_components\jquery.maskedinput\dist\jquery.maskedinput.min.js <
-- Not Found
   - public\dist\plugins\fileuploads\fileupload.min.js
   - public\dist\plugins\fileuploads\holder.min.js
   - public\dist\js\pds.js

Saving To...
   - public/js/pds.js

[19:43:23] gulp-notify: [Laravel Elixir] Scripts Merged!
[19:43:23] Finished 'scripts' after 1.55 s
[19:43:23] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\bower_components\fullcalendar\dist\fullcalendar.min.js <-- Not Found

   - public\bower_components\fullcalendar\dist\gcal.js <-- Not Found
   - public\dist\js\calendar.js

Saving To...
   - public/js/calendar.js

[19:43:23] gulp-notify: [Laravel Elixir] Scripts Merged!
[19:43:23] Finished 'scripts' after 37 ms
[19:43:23] Starting 'scripts'...

Fetching Scripts Source Files...
   - public\bower_components\datatables\media\js\jquery.datatables.min.js <-- No
t Found
   - public\bower_components\datatables\media\js\datatables.bootstrap.min.js <--
 Not Found
   - public\bower_components\datatables-responsive\js\datatables.responsive.js <
-- Not Found
   - public\dist\js\datatables.js

Saving To...
   - public/js/datatables.js

[19:43:23] gulp-notify: [Laravel Elixir] Scripts Merged!
[19:43:23] Finished 'scripts' after 39 ms
[19:43:23] Starting 'browserify'...

Fetching Browserify Source Files...
   - vue\app.js

Saving To...
   - public/js/app.min.js

[19:43:23] gulp-notify: [Laravel Elixir] Browserify Failed!: Couldn't find prese
t "es2015" relative to directory "C:\\xampp\\htdocs\\hris\\vue" while parsi
ng file: C:\xampp\htdocs\hris\vue\app.js
{ [Error: Couldn't find preset "es2015" relative to directory "C:\\xampp\\htdocs
\\rpdo-hris\\vue" while parsing file: C:\xampp\htdocs\hris\vue\app.js]
  filename: 'C:\\xampp\\htdocs\\hris\\vue\\app.js',

**Comment by rosemalejohn** [comment]
Try running bower install.

**Comment by picepice** [comment]
bower enoent no bower.json present

**Comment by rosemalejohn** [comment]
Please run `bower install` on the root directory of the project where bower.json is placed.

**Comment by rosemalejohn** [comment]
Sorry my mistake, please change directory to the public directory and run `bower install`

**Comment by picepice** [comment]
i think bower.json is not included.. i create `bower init` and run `bower install` but still no luck

**Comment by rosemalejohn** [comment]
Go to public directory and there you will find the bower.json file. Run from there `bower install`

**Comment by picepice** [comment]
thanks alot man.. first time to install laravel.. ill try to study your system.. 👍

**Comment by rosemalejohn** [comment]
No problem bud. Hope it can help you what you are trying to achieve. 😀😁😂
